//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordenadorSeccao
    {
        public string siglaSeccao { get; set; }
        public decimal ccProfessor { get; set; }
        public string siglaDepartamento { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Seccao Seccao { get; set; }
    }
}
