//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditosCurso
    {
        public string siglaCurso { get; set; }
        public string siglaUC { get; set; }
        public Nullable<decimal> numCreditos { get; set; }
    }
}
