//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TP1Entities : DbContext
    {
        public TP1Entities()
            : base("name=TP1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Ano> Ano { get; set; }
        public virtual DbSet<ConclusaoCurso> ConclusaoCurso { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Inscricao> Inscricao { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Professor_UC> Professor_UC { get; set; }
        public virtual DbSet<RegenteUC> RegenteUC { get; set; }
        public virtual DbSet<Seccao> Seccao { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<SemestreLetivo> SemestreLetivo { get; set; }
        public virtual DbSet<UC_Semestre> UC_Semestre { get; set; }
        public virtual DbSet<UnidadeCurricular> UnidadeCurricular { get; set; }
    
        public virtual ObjectResult<Nullable<int>> alunosMatriculadosMaisTresAnos(Nullable<decimal> currentYear, string siglaCurso)
        {
            var currentYearParameter = currentYear.HasValue ?
                new ObjectParameter("currentYear", currentYear) :
                new ObjectParameter("currentYear", typeof(decimal));
    
            var siglaCursoParameter = siglaCurso != null ?
                new ObjectParameter("siglaCurso", siglaCurso) :
                new ObjectParameter("siglaCurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("alunosMatriculadosMaisTresAnos", currentYearParameter, siglaCursoParameter);
        }
    
        public virtual int estruturaCurso(string siglaDepartamento, string siglaCurso, string descricaoCurso)
        {
            var siglaDepartamentoParameter = siglaDepartamento != null ?
                new ObjectParameter("siglaDepartamento", siglaDepartamento) :
                new ObjectParameter("siglaDepartamento", typeof(string));
    
            var siglaCursoParameter = siglaCurso != null ?
                new ObjectParameter("siglaCurso", siglaCurso) :
                new ObjectParameter("siglaCurso", typeof(string));
    
            var descricaoCursoParameter = descricaoCurso != null ?
                new ObjectParameter("descricaoCurso", descricaoCurso) :
                new ObjectParameter("descricaoCurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estruturaCurso", siglaDepartamentoParameter, siglaCursoParameter, descricaoCursoParameter);
        }
    
        public virtual int inscrever_Aluno_UC(Nullable<int> numAluno, string siglaUC, Nullable<decimal> ano)
        {
            var numAlunoParameter = numAluno.HasValue ?
                new ObjectParameter("numAluno", numAluno) :
                new ObjectParameter("numAluno", typeof(int));
    
            var siglaUCParameter = siglaUC != null ?
                new ObjectParameter("siglaUC", siglaUC) :
                new ObjectParameter("siglaUC", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inscrever_Aluno_UC", numAlunoParameter, siglaUCParameter, anoParameter);
        }
    
        public virtual int insert_Aluno_Curso(Nullable<int> numAluno, string siglaCurso, Nullable<decimal> ano)
        {
            var numAlunoParameter = numAluno.HasValue ?
                new ObjectParameter("numAluno", numAluno) :
                new ObjectParameter("numAluno", typeof(int));
    
            var siglaCursoParameter = siglaCurso != null ?
                new ObjectParameter("siglaCurso", siglaCurso) :
                new ObjectParameter("siglaCurso", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Aluno_Curso", numAlunoParameter, siglaCursoParameter, anoParameter);
        }
    
        public virtual int insert_Departamento(string new_sigla, string new_descricao)
        {
            var new_siglaParameter = new_sigla != null ?
                new ObjectParameter("new_sigla", new_sigla) :
                new ObjectParameter("new_sigla", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Departamento", new_siglaParameter, new_descricaoParameter);
        }
    
        public virtual int insert_nota(Nullable<int> numAluno, string siglaUC, Nullable<decimal> nota, Nullable<decimal> ano)
        {
            var numAlunoParameter = numAluno.HasValue ?
                new ObjectParameter("numAluno", numAluno) :
                new ObjectParameter("numAluno", typeof(int));
    
            var siglaUCParameter = siglaUC != null ?
                new ObjectParameter("siglaUC", siglaUC) :
                new ObjectParameter("siglaUC", typeof(string));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(decimal));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_nota", numAlunoParameter, siglaUCParameter, notaParameter, anoParameter);
        }
    
        public virtual int insert_Seccao(string new_sigla, string new_siglaDep, string new_descricao)
        {
            var new_siglaParameter = new_sigla != null ?
                new ObjectParameter("new_sigla", new_sigla) :
                new ObjectParameter("new_sigla", typeof(string));
    
            var new_siglaDepParameter = new_siglaDep != null ?
                new ObjectParameter("new_siglaDep", new_siglaDep) :
                new ObjectParameter("new_siglaDep", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Seccao", new_siglaParameter, new_siglaDepParameter, new_descricaoParameter);
        }
    
        public virtual int insert_UC(string new_sigla, string new_descricao, Nullable<decimal> nrCreditos)
        {
            var new_siglaParameter = new_sigla != null ?
                new ObjectParameter("new_sigla", new_sigla) :
                new ObjectParameter("new_sigla", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            var nrCreditosParameter = nrCreditos.HasValue ?
                new ObjectParameter("nrCreditos", nrCreditos) :
                new ObjectParameter("nrCreditos", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_UC", new_siglaParameter, new_descricaoParameter, nrCreditosParameter);
        }
    
        public virtual int insert_UC_Curso(Nullable<decimal> numSemestre, string siglaCurso, string siglaUC, Nullable<decimal> ano)
        {
            var numSemestreParameter = numSemestre.HasValue ?
                new ObjectParameter("numSemestre", numSemestre) :
                new ObjectParameter("numSemestre", typeof(decimal));
    
            var siglaCursoParameter = siglaCurso != null ?
                new ObjectParameter("siglaCurso", siglaCurso) :
                new ObjectParameter("siglaCurso", typeof(string));
    
            var siglaUCParameter = siglaUC != null ?
                new ObjectParameter("siglaUC", siglaUC) :
                new ObjectParameter("siglaUC", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_UC_Curso", numSemestreParameter, siglaCursoParameter, siglaUCParameter, anoParameter);
        }
    
        public virtual ObjectResult<listUCwithNoInsc_Result> listUCwithNoInsc(Nullable<decimal> anoInicial, Nullable<decimal> anoFinal)
        {
            var anoInicialParameter = anoInicial.HasValue ?
                new ObjectParameter("anoInicial", anoInicial) :
                new ObjectParameter("anoInicial", typeof(decimal));
    
            var anoFinalParameter = anoFinal.HasValue ?
                new ObjectParameter("anoFinal", anoFinal) :
                new ObjectParameter("anoFinal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listUCwithNoInsc_Result>("listUCwithNoInsc", anoInicialParameter, anoFinalParameter);
        }
    
        public virtual int remove_Departamento(string sigla)
        {
            var siglaParameter = sigla != null ?
                new ObjectParameter("sigla", sigla) :
                new ObjectParameter("sigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remove_Departamento", siglaParameter);
        }
    
        public virtual int remove_Seccao(string sigla, string siglaDepartamento)
        {
            var siglaParameter = sigla != null ?
                new ObjectParameter("sigla", sigla) :
                new ObjectParameter("sigla", typeof(string));
    
            var siglaDepartamentoParameter = siglaDepartamento != null ?
                new ObjectParameter("siglaDepartamento", siglaDepartamento) :
                new ObjectParameter("siglaDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remove_Seccao", siglaParameter, siglaDepartamentoParameter);
        }
    
        public virtual int remove_UC(string sigla)
        {
            var siglaParameter = sigla != null ?
                new ObjectParameter("sigla", sigla) :
                new ObjectParameter("sigla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remove_UC", siglaParameter);
        }
    
        public virtual int remove_UC_Curso(string siglaCurso, string siglaUC, Nullable<decimal> ano)
        {
            var siglaCursoParameter = siglaCurso != null ?
                new ObjectParameter("siglaCurso", siglaCurso) :
                new ObjectParameter("siglaCurso", typeof(string));
    
            var siglaUCParameter = siglaUC != null ?
                new ObjectParameter("siglaUC", siglaUC) :
                new ObjectParameter("siglaUC", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remove_UC_Curso", siglaCursoParameter, siglaUCParameter, anoParameter);
        }
    
        public virtual int update_Departamento(string sigla, string new_descricao)
        {
            var siglaParameter = sigla != null ?
                new ObjectParameter("sigla", sigla) :
                new ObjectParameter("sigla", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Departamento", siglaParameter, new_descricaoParameter);
        }
    
        public virtual int update_Seccao(string sigla2update, string new_siglaDep, string new_descricao)
        {
            var sigla2updateParameter = sigla2update != null ?
                new ObjectParameter("sigla2update", sigla2update) :
                new ObjectParameter("sigla2update", typeof(string));
    
            var new_siglaDepParameter = new_siglaDep != null ?
                new ObjectParameter("new_siglaDep", new_siglaDep) :
                new ObjectParameter("new_siglaDep", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Seccao", sigla2updateParameter, new_siglaDepParameter, new_descricaoParameter);
        }
    
        public virtual int update_UC(string uC2update, string new_descricao, Nullable<decimal> new_numCreditos)
        {
            var uC2updateParameter = uC2update != null ?
                new ObjectParameter("UC2update", uC2update) :
                new ObjectParameter("UC2update", typeof(string));
    
            var new_descricaoParameter = new_descricao != null ?
                new ObjectParameter("new_descricao", new_descricao) :
                new ObjectParameter("new_descricao", typeof(string));
    
            var new_numCreditosParameter = new_numCreditos.HasValue ?
                new ObjectParameter("new_numCreditos", new_numCreditos) :
                new ObjectParameter("new_numCreditos", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_UC", uC2updateParameter, new_descricaoParameter, new_numCreditosParameter);
        }
    }
}
