//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.Professor_UC = new HashSet<Professor_UC>();
            this.RegenteUCs = new HashSet<RegenteUC>();
        }
    
        public decimal cc { get; set; }
        public string nome { get; set; }
        public string areaEspecializacao { get; set; }
        public string categoria { get; set; }
        public string siglaDepartamento { get; set; }
        public string siglaSeccao { get; set; }
    
        public virtual CoordenadorSeccao CoordenadorSeccao { get; set; }
        public virtual Seccao Seccao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor_UC> Professor_UC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegenteUC> RegenteUCs { get; set; }
    }
}
