//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UC_Semestre
    {
        public decimal numSemestre { get; set; }
        public string siglaCurso { get; set; }
        public string siglaUC { get; set; }
        public decimal ano { get; set; }
    
        public virtual Ano Ano1 { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual UnidadeCurricular UnidadeCurricular { get; set; }
    }
}
